repos:
  - repo: git://github.com/golangci/golangci-lint
    rev: v1.33.0
    hooks:
      - id: golangci-lint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: no-commit-to-branch
        args: [--branch, main, --branch, cw2, --pattern, '\d\.\d\.\d']
      - id: trailing-whitespace
        exclude: poc

  - repo: git://github.com/igorshubovych/markdownlint-cli
    rev: v0.25.0
    hooks:
      - id: markdownlint